# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'periodictable.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PeriodicTable(object):
    def setupUi(self, PeriodicTable):
        PeriodicTable.setObjectName("PeriodicTable")
        PeriodicTable.resize(570, 300)
        font = QtGui.QFont()
        font.setPointSize(13)
        #font.setBold(False)
        font.setWeight(75)
        PeriodicTable.setFont(font)
        self.Refresh = QtWidgets.QPushButton(PeriodicTable)
        self.Refresh.setGeometry(QtCore.QRect(120, 10, 82, 40))
        self.Refresh.setCheckable(False)
        self.Clear = QtWidgets.QPushButton(PeriodicTable)
        self.Clear.setGeometry(QtCore.QRect(200, 10, 82, 40))
        self.Clear.setCheckable(False)
        self.ebtnHe = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnHe.setGeometry(QtCore.QRect(520, 10, 42, 40))
        self.ebtnHe.setCheckable(True)
        self.ebtnHe.setObjectName("ebtnHe")
        self.ebtnRa = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnRa.setGeometry(QtCore.QRect(40, 190, 42, 40))
        self.ebtnRa.setCheckable(True)
        self.ebtnRa.setObjectName("ebtnRa")
        self.ebtnLu = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnLu.setGeometry(QtCore.QRect(520, 230, 42, 40))
        self.ebtnLu.setCheckable(True)
        self.ebtnLu.setObjectName("ebtnLu")
        self.ebtnGa = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnGa.setGeometry(QtCore.QRect(370, 100, 42, 40))
        self.ebtnGa.setCheckable(True)
        self.ebtnGa.setObjectName("ebtnGa")
        self.ebtnCa = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnCa.setGeometry(QtCore.QRect(40, 100, 42, 40))
        self.ebtnCa.setCheckable(True)
        self.ebtnCa.setObjectName("ebtnCa")
        self.ebtnAu = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnAu.setGeometry(QtCore.QRect(310, 160, 42, 40))
        self.ebtnAu.setCheckable(True)
        self.ebtnAu.setObjectName("ebtnAu")
        self.ebtnLa = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnLa.setGeometry(QtCore.QRect(100, 230, 42, 40))
        self.ebtnLa.setCheckable(True)
        self.ebtnLa.setObjectName("ebtnLa")
        self.ebtnYb = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnYb.setGeometry(QtCore.QRect(490, 230, 42, 40))
        self.ebtnYb.setCheckable(True)
        self.ebtnYb.setObjectName("ebtnYb")
        self.ebtnW = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnW.setGeometry(QtCore.QRect(160, 160, 42, 40))
        self.ebtnW.setCheckable(True)
        self.ebtnW.setObjectName("ebtnW")
        self.ebtnBk = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnBk.setGeometry(QtCore.QRect(340, 260, 42, 40))
        self.ebtnBk.setCheckable(True)
        self.ebtnBk.setObjectName("ebtnBk")
        self.ebtnSc = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnSc.setGeometry(QtCore.QRect(70, 100, 42, 40))
        self.ebtnSc.setCheckable(True)
        self.ebtnSc.setObjectName("ebtnSc")
        self.ebtnNi = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnNi.setGeometry(QtCore.QRect(280, 100, 42, 40))
        self.ebtnNi.setCheckable(True)
        self.ebtnNi.setObjectName("ebtnNi")
        self.ebtnBa = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnBa.setGeometry(QtCore.QRect(40, 160, 42, 40))
        self.ebtnBa.setCheckable(True)
        self.ebtnBa.setObjectName("ebtnBa")
        self.ebtnBh = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnBh.setGeometry(QtCore.QRect(190, 190, 42, 40))
        self.ebtnBh.setCheckable(True)
        self.ebtnBh.setObjectName("ebtnBh")
        self.ebtnHs = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnHs.setGeometry(QtCore.QRect(220, 190, 42, 40))
        self.ebtnHs.setCheckable(True)
        self.ebtnHs.setObjectName("ebtnHs")
        self.ebtnHf = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnHf.setGeometry(QtCore.QRect(100, 160, 42, 40))
        self.ebtnHf.setCheckable(True)
        self.ebtnHf.setObjectName("ebtnHf")
        self.ebtnPr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnPr.setGeometry(QtCore.QRect(160, 230, 42, 40))
        self.ebtnPr.setCheckable(True)
        self.ebtnPr.setObjectName("ebtnPr")
        self.ebtnV = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnV.setGeometry(QtCore.QRect(130, 100, 42, 40))
        self.ebtnV.setCheckable(True)
        self.ebtnV.setObjectName("ebtnV")
        self.ebtnN = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnN.setGeometry(QtCore.QRect(430, 40, 42, 40))
        self.ebtnN.setCheckable(True)
        self.ebtnN.setObjectName("ebtnN")
        self.ebtnFr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnFr.setGeometry(QtCore.QRect(10, 190, 42, 40))
        self.ebtnFr.setCheckable(True)
        self.ebtnFr.setObjectName("ebtnFr")
        self.ebtnGd = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnGd.setGeometry(QtCore.QRect(310, 230, 42, 40))
        self.ebtnGd.setCheckable(True)
        self.ebtnGd.setObjectName("ebtnGd")
        self.ebtnO = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnO.setGeometry(QtCore.QRect(460, 40, 42, 40))
        self.ebtnO.setCheckable(True)
        self.ebtnO.setObjectName("ebtnO")
        self.ebtnPt = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnPt.setGeometry(QtCore.QRect(280, 160, 42, 40))
        self.ebtnPt.setCheckable(True)
        self.ebtnPt.setObjectName("ebtnPt")
        self.ebtnLi = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnLi.setGeometry(QtCore.QRect(10, 40, 42, 40))
        self.ebtnLi.setCheckable(True)
        self.ebtnLi.setObjectName("ebtnLi")
        self.ebtnP = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnP.setGeometry(QtCore.QRect(430, 70, 42, 40))
        self.ebtnP.setCheckable(True)
        self.ebtnP.setObjectName("ebtnP")
        self.ebtnXe = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnXe.setGeometry(QtCore.QRect(520, 130, 42, 40))
        self.ebtnXe.setCheckable(True)
        self.ebtnXe.setObjectName("ebtnXe")
        self.ebtnPd = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnPd.setGeometry(QtCore.QRect(280, 130, 42, 40))
        self.ebtnPd.setCheckable(True)
        self.ebtnPd.setObjectName("ebtnPd")
        self.ebtnDb = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnDb.setGeometry(QtCore.QRect(130, 190, 42, 40))
        self.ebtnDb.setCheckable(True)
        self.ebtnDb.setObjectName("ebtnDb")
        self.ebtnRb = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnRb.setGeometry(QtCore.QRect(10, 130, 42, 40))
        self.ebtnRb.setCheckable(True)
        self.ebtnRb.setObjectName("ebtnRb")
        self.ebtnBi = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnBi.setGeometry(QtCore.QRect(430, 160, 42, 40))
        self.ebtnBi.setCheckable(True)
        self.ebtnBi.setObjectName("ebtnBi")
        self.ebtnIn = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnIn.setGeometry(QtCore.QRect(370, 130, 42, 40))
        self.ebtnIn.setCheckable(True)
        self.ebtnIn.setObjectName("ebtnIn")
        self.ebtnS = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnS.setGeometry(QtCore.QRect(460, 70, 42, 40))
        self.ebtnS.setCheckable(True)
        self.ebtnS.setObjectName("ebtnS")
        self.ebtnNd = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnNd.setGeometry(QtCore.QRect(190, 230, 42, 40))
        self.ebtnNd.setCheckable(True)
        self.ebtnNd.setObjectName("ebtnNd")
        self.ebtnNa = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnNa.setGeometry(QtCore.QRect(10, 70, 42, 40))
        self.ebtnNa.setCheckable(True)
        self.ebtnNa.setObjectName("ebtnNa")
        self.ebtnIr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnIr.setGeometry(QtCore.QRect(250, 160, 42, 40))
        self.ebtnIr.setCheckable(True)
        self.ebtnIr.setObjectName("ebtnIr")
        self.ebtnOs = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnOs.setGeometry(QtCore.QRect(220, 160, 42, 40))
        self.ebtnOs.setCheckable(True)
        self.ebtnOs.setObjectName("ebtnOs")
        self.ebtnPu = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnPu.setGeometry(QtCore.QRect(250, 260, 42, 40))
        self.ebtnPu.setCheckable(True)
        self.ebtnPu.setObjectName("ebtnPu")
        self.ebtnTe = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnTe.setGeometry(QtCore.QRect(460, 130, 42, 40))
        self.ebtnTe.setCheckable(True)
        self.ebtnTe.setObjectName("ebtnTe")
        self.ebtnEs = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnEs.setGeometry(QtCore.QRect(400, 260, 42, 40))
        self.ebtnEs.setCheckable(True)
        self.ebtnEs.setObjectName("ebtnEs")
        self.ebtnCe = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnCe.setGeometry(QtCore.QRect(130, 230, 42, 40))
        self.ebtnCe.setCheckable(True)
        self.ebtnCe.setObjectName("ebtnCe")
        self.ebtnB = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnB.setGeometry(QtCore.QRect(370, 40, 42, 40))
        self.ebtnB.setCheckable(True)
        self.ebtnB.setObjectName("ebtnB")
        self.ebtnRe = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnRe.setGeometry(QtCore.QRect(190, 160, 42, 40))
        self.ebtnRe.setCheckable(True)
        self.ebtnRe.setObjectName("ebtnRe")
        self.ebtnCs = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnCs.setGeometry(QtCore.QRect(10, 160, 42, 40))
        self.ebtnCs.setCheckable(True)
        self.ebtnCs.setObjectName("ebtnCs")
        self.ebtnCd = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnCd.setGeometry(QtCore.QRect(340, 130, 42, 40))
        self.ebtnCd.setCheckable(True)
        self.ebtnCd.setObjectName("ebtnCd")
        self.ebtnPb = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnPb.setGeometry(QtCore.QRect(400, 160, 42, 40))
        self.ebtnPb.setCheckable(True)
        self.ebtnPb.setObjectName("ebtnPb")
        self.ebtnRn = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnRn.setGeometry(QtCore.QRect(520, 160, 42, 40))
        self.ebtnRn.setCheckable(True)
        self.ebtnRn.setObjectName("ebtnRn")
        self.ebtnY = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnY.setGeometry(QtCore.QRect(70, 130, 42, 40))
        self.ebtnY.setCheckable(True)
        self.ebtnY.setObjectName("ebtnY")
        self.ebtnU = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnU.setGeometry(QtCore.QRect(190, 260, 42, 40))
        self.ebtnU.setCheckable(True)
        self.ebtnU.setObjectName("ebtnU")
        self.ebtnBr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnBr.setGeometry(QtCore.QRect(490, 100, 42, 40))
        self.ebtnBr.setCheckable(True)
        self.ebtnBr.setObjectName("ebtnBr")
        self.ebtnC = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnC.setGeometry(QtCore.QRect(400, 40, 42, 40))
        self.ebtnC.setCheckable(True)
        self.ebtnC.setObjectName("ebtnC")
        self.ebtnHo = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnHo.setGeometry(QtCore.QRect(400, 230, 42, 40))
        self.ebtnHo.setCheckable(True)
        self.ebtnHo.setObjectName("ebtnHo")
        self.ebtnNp = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnNp.setGeometry(QtCore.QRect(220, 260, 42, 40))
        self.ebtnNp.setCheckable(True)
        self.ebtnNp.setObjectName("ebtnNp")
        self.ebtnEu = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnEu.setGeometry(QtCore.QRect(280, 230, 42, 40))
        self.ebtnEu.setCheckable(True)
        self.ebtnEu.setObjectName("ebtnEu")
        self.ebtnMn = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnMn.setGeometry(QtCore.QRect(190, 100, 42, 40))
        self.ebtnMn.setCheckable(True)
        self.ebtnMn.setObjectName("ebtnMn")
        self.ebtnGe = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnGe.setGeometry(QtCore.QRect(400, 100, 42, 40))
        self.ebtnGe.setCheckable(True)
        self.ebtnGe.setObjectName("ebtnGe")
        self.ebtnAc = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnAc.setEnabled(True)
        self.ebtnAc.setGeometry(QtCore.QRect(100, 260, 42, 40))
        self.ebtnAc.setAcceptDrops(False)
        self.ebtnAc.setCheckable(True)
        self.ebtnAc.setChecked(False)
        self.ebtnAc.setAutoDefault(False)
        self.ebtnAc.setObjectName("ebtnAc")
        self.ebtnAl = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnAl.setGeometry(QtCore.QRect(370, 70, 42, 40))
        self.ebtnAl.setCheckable(True)
        self.ebtnAl.setObjectName("ebtnAl")
        self.ebtnSr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnSr.setGeometry(QtCore.QRect(40, 130, 42, 40))
        self.ebtnSr.setCheckable(True)
        self.ebtnSr.setObjectName("ebtnSr")
        self.ebtnPo = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnPo.setGeometry(QtCore.QRect(460, 160, 42, 40))
        self.ebtnPo.setCheckable(True)
        self.ebtnPo.setObjectName("ebtnPo")
        self.ebtnH = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnH.setGeometry(QtCore.QRect(10, 10, 42, 40))
        self.ebtnH.setCheckable(True)
        self.ebtnH.setObjectName("ebtnH")
        self.ebtnMg = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnMg.setGeometry(QtCore.QRect(40, 70, 42, 40))
        self.ebtnMg.setCheckable(True)
        self.ebtnMg.setObjectName("ebtnMg")
        self.ebtnNb = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnNb.setGeometry(QtCore.QRect(130, 130, 42, 40))
        self.ebtnNb.setCheckable(True)
        self.ebtnNb.setObjectName("ebtnNb")
        self.ebtnSe = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnSe.setGeometry(QtCore.QRect(460, 100, 42, 40))
        self.ebtnSe.setCheckable(True)
        self.ebtnSe.setObjectName("ebtnSe")
        self.ebtnFm = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnFm.setGeometry(QtCore.QRect(430, 260, 42, 40))
        self.ebtnFm.setCheckable(True)
        self.ebtnFm.setObjectName("ebtnFm")
        self.ebtnRu = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnRu.setGeometry(QtCore.QRect(220, 130, 42, 40))
        self.ebtnRu.setCheckable(True)
        self.ebtnRu.setObjectName("ebtnRu")
        self.ebtnZr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnZr.setGeometry(QtCore.QRect(100, 130, 42, 40))
        self.ebtnZr.setCheckable(True)
        self.ebtnZr.setObjectName("ebtnZr")
        self.ebtnCm = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnCm.setGeometry(QtCore.QRect(310, 260, 42, 40))
        self.ebtnCm.setCheckable(True)
        self.ebtnCm.setObjectName("ebtnCm")
        self.ebtnAm = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnAm.setGeometry(QtCore.QRect(280, 260, 42, 40))
        self.ebtnAm.setCheckable(True)
        self.ebtnAm.setObjectName("ebtnAm")
        self.ebtnNo = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnNo.setGeometry(QtCore.QRect(490, 260, 42, 40))
        self.ebtnNo.setCheckable(True)
        self.ebtnNo.setObjectName("ebtnNo")
        self.ebtnMt = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnMt.setGeometry(QtCore.QRect(250, 190, 42, 40))
        self.ebtnMt.setCheckable(True)
        self.ebtnMt.setObjectName("ebtnMt")
        self.ebtnTh = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnTh.setGeometry(QtCore.QRect(130, 260, 42, 40))
        self.ebtnTh.setCheckable(True)
        self.ebtnTh.setObjectName("ebtnTh")
        self.ebtnK = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnK.setGeometry(QtCore.QRect(10, 100, 42, 40))
        self.ebtnK.setCheckable(True)
        self.ebtnK.setObjectName("ebtnK")
        self.ebtnMo = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnMo.setGeometry(QtCore.QRect(160, 130, 42, 40))
        self.ebtnMo.setCheckable(True)
        self.ebtnMo.setObjectName("ebtnMo")
        self.ebtnF = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnF.setGeometry(QtCore.QRect(490, 40, 42, 40))
        self.ebtnF.setCheckable(True)
        self.ebtnF.setObjectName("ebtnF")
        self.ebtnTc = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnTc.setGeometry(QtCore.QRect(190, 130, 42, 40))
        self.ebtnTc.setCheckable(True)
        self.ebtnTc.setObjectName("ebtnTc")
        self.ebtnNe = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnNe.setGeometry(QtCore.QRect(520, 40, 42, 40))
        self.ebtnNe.setCheckable(True)
        self.ebtnNe.setObjectName("ebtnNe")
        self.ebtnCo = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnCo.setGeometry(QtCore.QRect(250, 100, 42, 40))
        self.ebtnCo.setCheckable(True)
        self.ebtnCo.setObjectName("ebtnCo")
        self.ebtnMd = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnMd.setGeometry(QtCore.QRect(460, 260, 42, 40))
        self.ebtnMd.setCheckable(True)
        self.ebtnMd.setObjectName("ebtnMd")
        self.ebtnSb = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnSb.setGeometry(QtCore.QRect(430, 130, 42, 40))
        self.ebtnSb.setCheckable(True)
        self.ebtnSb.setObjectName("ebtnSb")
        self.ebtnTb = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnTb.setGeometry(QtCore.QRect(340, 230, 42, 40))
        self.ebtnTb.setCheckable(True)
        self.ebtnTb.setObjectName("ebtnTb")
        self.ebtnTm = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnTm.setGeometry(QtCore.QRect(460, 230, 42, 40))
        self.ebtnTm.setCheckable(True)
        self.ebtnTm.setObjectName("ebtnTm")
        self.ebtnEr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnEr.setGeometry(QtCore.QRect(430, 230, 42, 40))
        self.ebtnEr.setCheckable(True)
        self.ebtnEr.setObjectName("ebtnEr")
        self.ebtnCl = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnCl.setGeometry(QtCore.QRect(490, 70, 42, 40))
        self.ebtnCl.setCheckable(True)
        self.ebtnCl.setObjectName("ebtnCl")
        self.ebtnAt = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnAt.setGeometry(QtCore.QRect(490, 160, 42, 40))
        self.ebtnAt.setCheckable(True)
        self.ebtnAt.setObjectName("ebtnAt")
        self.ebtnCr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnCr.setGeometry(QtCore.QRect(160, 100, 42, 40))
        self.ebtnCr.setCheckable(True)
        self.ebtnCr.setObjectName("ebtnCr")
        self.ebtnTa = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnTa.setGeometry(QtCore.QRect(130, 160, 42, 40))
        self.ebtnTa.setCheckable(True)
        self.ebtnTa.setObjectName("ebtnTa")
        self.ebtnRh = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnRh.setGeometry(QtCore.QRect(250, 130, 42, 40))
        self.ebtnRh.setCheckable(True)
        self.ebtnRh.setObjectName("ebtnRh")
        self.ebtnI = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnI.setGeometry(QtCore.QRect(490, 130, 42, 40))
        self.ebtnI.setCheckable(True)
        self.ebtnI.setObjectName("ebtnI")
        self.ebtnTl = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnTl.setGeometry(QtCore.QRect(370, 160, 42, 40))
        self.ebtnTl.setCheckable(True)
        self.ebtnTl.setObjectName("ebtnTl")
        self.ebtnSn = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnSn.setGeometry(QtCore.QRect(400, 130, 42, 40))
        self.ebtnSn.setCheckable(True)
        self.ebtnSn.setObjectName("ebtnSn")
        self.ebtnPa = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnPa.setGeometry(QtCore.QRect(160, 260, 42, 40))
        self.ebtnPa.setCheckable(True)
        self.ebtnPa.setObjectName("ebtnPa")
        self.ebtnAr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnAr.setGeometry(QtCore.QRect(520, 70, 42, 40))
        self.ebtnAr.setCheckable(True)
        self.ebtnAr.setObjectName("ebtnAr")
        self.ebtnSi = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnSi.setGeometry(QtCore.QRect(400, 70, 42, 40))
        self.ebtnSi.setCheckable(True)
        self.ebtnSi.setObjectName("ebtnSi")
        self.ebtnSm = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnSm.setGeometry(QtCore.QRect(250, 230, 42, 40))
        self.ebtnSm.setCheckable(True)
        self.ebtnSm.setObjectName("ebtnSm")
        self.ebtnFe = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnFe.setGeometry(QtCore.QRect(220, 100, 42, 40))
        self.ebtnFe.setCheckable(True)
        self.ebtnFe.setObjectName("ebtnFe")
        self.ebtnKr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnKr.setGeometry(QtCore.QRect(520, 100, 42, 40))
        self.ebtnKr.setCheckable(True)
        self.ebtnKr.setObjectName("ebtnKr")
        self.ebtnBe = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnBe.setGeometry(QtCore.QRect(40, 40, 42, 40))
        self.ebtnBe.setCheckable(True)
        self.ebtnBe.setObjectName("ebtnBe")
        self.ebtnRf = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnRf.setGeometry(QtCore.QRect(100, 190, 42, 40))
        self.ebtnRf.setCheckable(True)
        self.ebtnRf.setObjectName("ebtnRf")
        self.ebtnLr = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnLr.setGeometry(QtCore.QRect(520, 260, 42, 40))
        self.ebtnLr.setCheckable(True)
        self.ebtnLr.setObjectName("ebtnLr")
        self.ebtnSg = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnSg.setGeometry(QtCore.QRect(160, 190, 42, 40))
        self.ebtnSg.setCheckable(True)
        self.ebtnSg.setObjectName("ebtnSg")
        self.ebtnHg = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnHg.setGeometry(QtCore.QRect(340, 160, 42, 40))
        self.ebtnHg.setCheckable(True)
        self.ebtnHg.setObjectName("ebtnHg")
        self.ebtnAs = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnAs.setGeometry(QtCore.QRect(430, 100, 42, 40))
        self.ebtnAs.setCheckable(True)
        self.ebtnAs.setObjectName("ebtnAs")
        self.ebtnCu = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnCu.setGeometry(QtCore.QRect(310, 100, 42, 40))
        self.ebtnCu.setCheckable(True)
        self.ebtnCu.setObjectName("ebtnCu")
        self.ebtnCf = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnCf.setGeometry(QtCore.QRect(370, 260, 42, 40))
        self.ebtnCf.setCheckable(True)
        self.ebtnCf.setObjectName("ebtnCf")
        self.ebtnTi = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnTi.setGeometry(QtCore.QRect(100, 100, 42, 40))
        self.ebtnTi.setCheckable(True)
        self.ebtnTi.setObjectName("ebtnTi")
        self.ebtnDy = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnDy.setGeometry(QtCore.QRect(370, 230, 42, 40))
        self.ebtnDy.setCheckable(True)
        self.ebtnDy.setObjectName("ebtnDy")
        self.ebtnPm = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnPm.setGeometry(QtCore.QRect(220, 230, 42, 40))
        self.ebtnPm.setCheckable(True)
        self.ebtnPm.setObjectName("ebtnPm")
        self.ebtnAg = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnAg.setGeometry(QtCore.QRect(310, 130, 42, 40))
        self.ebtnAg.setCheckable(True)
        self.ebtnAg.setObjectName("ebtnAg")
        self.ebtnZn = QtWidgets.QPushButton(PeriodicTable)
        self.ebtnZn.setGeometry(QtCore.QRect(340, 100, 42, 40))
        self.ebtnZn.setCheckable(True)
        self.ebtnZn.setObjectName("ebtnZn")
        #self.label_3 = QtWidgets.QLabel(PeriodicTable)
        #self.label_3.setGeometry(QtCore.QRect(100, 10, 231, 20))
        #font = QtGui.QFont()
        #font.setPointSize(9)
        #font.setBold(True)
        #font.setWeight(75)
        #self.label_3.setFont(font)
        #self.label_3.setObjectName("label_3")
        #self.label_4 = QtWidgets.QLabel(PeriodicTable)
        #self.label_4.setGeometry(QtCore.QRect(580, 10, 231, 20))
        #font = QtGui.QFont()
        #font.setPointSize(9)
        #font.setBold(True)
        #font.setWeight(75)
        #self.label_4.setFont(font)
        #self.label_4.setObjectName("label_4")
        #self.ligCheckBox1 = QtWidgets.QCheckBox(PeriodicTable)
        #self.ligCheckBox1.setGeometry(QtCore.QRect(570, 73, 21, 17))
        #self.ligCheckBox1.setText("")
        #self.ligCheckBox1.setObjectName("ligCheckBox1")
        #self.ligFormula1 = QtWidgets.QLineEdit(PeriodicTable)
        #self.ligFormula1.setGeometry(QtCore.QRect(590, 71, 61, 20))
        #self.ligFormula1.setObjectName("ligFormula1")
        #self.ligMass1 = QtWidgets.QLineEdit(PeriodicTable)
        #self.ligMass1.setGeometry(QtCore.QRect(660, 71, 61, 20))
        #self.ligMass1.setReadOnly(True)
        #self.ligMass1.setObjectName("ligMass1")
        #self.ligClear1 = QtWidgets.QPushButton(PeriodicTable)
        #self.ligClear1.setGeometry(QtCore.QRect(740, 70, 21, 23))
        #self.ligClear1.setObjectName("ligClear1")
        #self.label_5 = QtWidgets.QLabel(PeriodicTable)
        #self.label_5.setGeometry(QtCore.QRect(590, 50, 231, 20))
        #font = QtGui.QFont()
        #font.setPointSize(9)
        #font.setBold(True)
        #font.setWeight(75)
        #self.label_5.setFont(font)
        #self.label_5.setObjectName("label_5")
        #self.label_6 = QtWidgets.QLabel(PeriodicTable)
        #self.label_6.setGeometry(QtCore.QRect(660, 50, 231, 20))
        #font = QtGui.QFont()
        #font.setPointSize(9)
        #font.setBold(True)
        #font.setWeight(75)
        #self.label_6.setFont(font)
        #self.label_6.setObjectName("label_6")
        #self.ligClear2 = QtWidgets.QPushButton(PeriodicTable)
        #self.ligClear2.setGeometry(QtCore.QRect(740, 109, 21, 23))
        #self.ligClear2.setObjectName("ligClear2")
        #self.ligCheckBox2 = QtWidgets.QCheckBox(PeriodicTable)
        #self.ligCheckBox2.setGeometry(QtCore.QRect(570, 112, 21, 17))
        #self.ligCheckBox2.setText("")
        #self.ligCheckBox2.setObjectName("ligCheckBox2")
        #self.ligFormula2 = QtWidgets.QLineEdit(PeriodicTable)
        #self.ligFormula2.setGeometry(QtCore.QRect(590, 110, 61, 20))
        #self.ligFormula2.setObjectName("ligFormula2")
        #self.ligMass2 = QtWidgets.QLineEdit(PeriodicTable)
        #self.ligMass2.setGeometry(QtCore.QRect(660, 110, 61, 20))
        #self.ligMass2.setReadOnly(True)
        #self.ligMass2.setObjectName("ligMass2")
        #self.ligMass3 = QtWidgets.QLineEdit(PeriodicTable)
        #self.ligMass3.setGeometry(QtCore.QRect(660, 150, 61, 20))
        #self.ligMass3.setReadOnly(True)
        #self.ligMass3.setObjectName("ligMass3")
        #self.ligClear3 = QtWidgets.QPushButton(PeriodicTable)
        #self.ligClear3.setGeometry(QtCore.QRect(740, 149, 21, 23))
        #self.ligClear3.setObjectName("ligClear3")
        #self.ligCheckBox3 = QtWidgets.QCheckBox(PeriodicTable)
        #self.ligCheckBox3.setGeometry(QtCore.QRect(570, 152, 21, 17))
        #self.ligCheckBox3.setText("")
        #self.ligCheckBox3.setObjectName("ligCheckBox3")
        #self.ligFormula3 = QtWidgets.QLineEdit(PeriodicTable)
        #self.ligFormula3.setGeometry(QtCore.QRect(590, 150, 61, 20))
        #self.ligFormula3.setObjectName("ligFormula3")

        self.retranslateUi(PeriodicTable)
        QtCore.QMetaObject.connectSlotsByName(PeriodicTable)

    def retranslateUi(self, PeriodicTable):
        _translate = QtCore.QCoreApplication.translate
        PeriodicTable.setWindowTitle(_translate("PeriodicTable", "PeriodicTable"))
        self.Refresh.setText(_translate("PeriodicTable", "Refresh"))
        self.Clear.setText(_translate("PeriodicTable", "Clear"))
        self.ebtnHe.setText(_translate("PeriodicTable", "He"))
        self.ebtnRa.setText(_translate("PeriodicTable", "Ra"))
        self.ebtnLu.setText(_translate("PeriodicTable", "Lu"))
        self.ebtnGa.setText(_translate("PeriodicTable", "Ga"))
        self.ebtnCa.setText(_translate("PeriodicTable", "Ca"))
        self.ebtnAu.setText(_translate("PeriodicTable", "Au"))
        self.ebtnLa.setText(_translate("PeriodicTable", "La"))
        self.ebtnYb.setText(_translate("PeriodicTable", "Yb"))
        self.ebtnW.setText(_translate("PeriodicTable", "W"))
        self.ebtnBk.setText(_translate("PeriodicTable", "Bk"))
        self.ebtnSc.setText(_translate("PeriodicTable", "Sc"))
        self.ebtnNi.setText(_translate("PeriodicTable", "Ni"))
        self.ebtnBa.setText(_translate("PeriodicTable", "Ba"))
        self.ebtnBh.setText(_translate("PeriodicTable", "Bh"))
        self.ebtnHs.setText(_translate("PeriodicTable", "Hs"))
        self.ebtnHf.setText(_translate("PeriodicTable", "Hf"))
        self.ebtnPr.setText(_translate("PeriodicTable", "Pr"))
        self.ebtnV.setText(_translate("PeriodicTable", "V"))
        self.ebtnN.setText(_translate("PeriodicTable", "N"))
        self.ebtnFr.setText(_translate("PeriodicTable", "Fr"))
        self.ebtnGd.setText(_translate("PeriodicTable", "Gd"))
        self.ebtnO.setText(_translate("PeriodicTable", "O"))
        self.ebtnPt.setText(_translate("PeriodicTable", "Pt"))
        self.ebtnLi.setText(_translate("PeriodicTable", "Li"))
        self.ebtnP.setText(_translate("PeriodicTable", "P"))
        self.ebtnXe.setText(_translate("PeriodicTable", "Xe"))
        self.ebtnPd.setText(_translate("PeriodicTable", "Pd"))
        self.ebtnDb.setText(_translate("PeriodicTable", "Db"))
        self.ebtnRb.setText(_translate("PeriodicTable", "Rb"))
        self.ebtnBi.setText(_translate("PeriodicTable", "Bi"))
        self.ebtnIn.setText(_translate("PeriodicTable", "In"))
        self.ebtnS.setText(_translate("PeriodicTable", "S"))
        self.ebtnNd.setText(_translate("PeriodicTable", "Nd"))
        self.ebtnNa.setText(_translate("PeriodicTable", "Na"))
        self.ebtnIr.setText(_translate("PeriodicTable", "Ir"))
        self.ebtnOs.setText(_translate("PeriodicTable", "Os"))
        self.ebtnPu.setText(_translate("PeriodicTable", "Pu"))
        self.ebtnTe.setText(_translate("PeriodicTable", "Te"))
        self.ebtnEs.setText(_translate("PeriodicTable", "Es"))
        self.ebtnCe.setText(_translate("PeriodicTable", "Ce"))
        self.ebtnB.setText(_translate("PeriodicTable", "B"))
        self.ebtnRe.setText(_translate("PeriodicTable", "Re"))
        self.ebtnCs.setText(_translate("PeriodicTable", "Cs"))
        self.ebtnCd.setText(_translate("PeriodicTable", "Cd"))
        self.ebtnPb.setText(_translate("PeriodicTable", "Pb"))
        self.ebtnRn.setText(_translate("PeriodicTable", "Rn"))
        self.ebtnY.setText(_translate("PeriodicTable", "Y"))
        self.ebtnU.setText(_translate("PeriodicTable", "U"))
        self.ebtnBr.setText(_translate("PeriodicTable", "Br"))
        self.ebtnC.setText(_translate("PeriodicTable", "C"))
        self.ebtnHo.setText(_translate("PeriodicTable", "Ho"))
        self.ebtnNp.setText(_translate("PeriodicTable", "Np"))
        self.ebtnEu.setText(_translate("PeriodicTable", "Eu"))
        self.ebtnMn.setText(_translate("PeriodicTable", "Mn"))
        self.ebtnGe.setText(_translate("PeriodicTable", "Ge"))
        self.ebtnAc.setText(_translate("PeriodicTable", "Ac"))
        self.ebtnAl.setText(_translate("PeriodicTable", "Al"))
        self.ebtnSr.setText(_translate("PeriodicTable", "Sr"))
        self.ebtnPo.setText(_translate("PeriodicTable", "Po"))
        self.ebtnH.setText(_translate("PeriodicTable", "H"))
        self.ebtnMg.setText(_translate("PeriodicTable", "Mg"))
        self.ebtnNb.setText(_translate("PeriodicTable", "Nb"))
        self.ebtnSe.setText(_translate("PeriodicTable", "Se"))
        self.ebtnFm.setText(_translate("PeriodicTable", "Fm"))
        self.ebtnRu.setText(_translate("PeriodicTable", "Ru"))
        self.ebtnZr.setText(_translate("PeriodicTable", "Zr"))
        self.ebtnCm.setText(_translate("PeriodicTable", "Cm"))
        self.ebtnAm.setText(_translate("PeriodicTable", "Am"))
        self.ebtnNo.setText(_translate("PeriodicTable", "No"))
        self.ebtnMt.setText(_translate("PeriodicTable", "Mt"))
        self.ebtnTh.setText(_translate("PeriodicTable", "Th"))
        self.ebtnK.setText(_translate("PeriodicTable", "K"))
        self.ebtnMo.setText(_translate("PeriodicTable", "Mo"))
        self.ebtnF.setText(_translate("PeriodicTable", "F"))
        self.ebtnTc.setText(_translate("PeriodicTable", "Tc"))
        self.ebtnNe.setText(_translate("PeriodicTable", "Ne"))
        self.ebtnCo.setText(_translate("PeriodicTable", "Co"))
        self.ebtnMd.setText(_translate("PeriodicTable", "Md"))
        self.ebtnSb.setText(_translate("PeriodicTable", "Sb"))
        self.ebtnTb.setText(_translate("PeriodicTable", "Tb"))
        self.ebtnTm.setText(_translate("PeriodicTable", "Tm"))
        self.ebtnEr.setText(_translate("PeriodicTable", "Er"))
        self.ebtnCl.setText(_translate("PeriodicTable", "Cl"))
        self.ebtnAt.setText(_translate("PeriodicTable", "At"))
        self.ebtnCr.setText(_translate("PeriodicTable", "Cr"))
        self.ebtnTa.setText(_translate("PeriodicTable", "Ta"))
        self.ebtnRh.setText(_translate("PeriodicTable", "Rh"))
        self.ebtnI.setText(_translate("PeriodicTable", "I"))
        self.ebtnTl.setText(_translate("PeriodicTable", "Tl"))
        self.ebtnSn.setText(_translate("PeriodicTable", "Sn"))
        self.ebtnPa.setText(_translate("PeriodicTable", "Pa"))
        self.ebtnAr.setText(_translate("PeriodicTable", "Ar"))
        self.ebtnSi.setText(_translate("PeriodicTable", "Si"))
        self.ebtnSm.setText(_translate("PeriodicTable", "Sm"))
        self.ebtnFe.setText(_translate("PeriodicTable", "Fe"))
        self.ebtnKr.setText(_translate("PeriodicTable", "Kr"))
        self.ebtnBe.setText(_translate("PeriodicTable", "Be"))
        self.ebtnRf.setText(_translate("PeriodicTable", "Rf"))
        self.ebtnLr.setText(_translate("PeriodicTable", "Lr"))
        self.ebtnSg.setText(_translate("PeriodicTable", "Sg"))
        self.ebtnHg.setText(_translate("PeriodicTable", "Hg"))
        self.ebtnAs.setText(_translate("PeriodicTable", "As"))
        self.ebtnCu.setText(_translate("PeriodicTable", "Cu"))
        self.ebtnCf.setText(_translate("PeriodicTable", "Cf"))
        self.ebtnTi.setText(_translate("PeriodicTable", "Ti"))
        self.ebtnDy.setText(_translate("PeriodicTable", "Dy"))
        self.ebtnPm.setText(_translate("PeriodicTable", "Pm"))
        self.ebtnAg.setText(_translate("PeriodicTable", "Ag"))
        self.ebtnZn.setText(_translate("PeriodicTable", "Zn"))
        #self.label_3.setText(_translate("PeriodicTable", "Step 1: Choose Elements To Include"))
        #self.label_4.setText(_translate("PeriodicTable", "Optional: Custom Ligand"))
        #self.ligClear1.setText(_translate("PeriodicTable", "x"))
        #self.label_5.setText(_translate("PeriodicTable", "Formula"))
        #self.label_6.setText(_translate("PeriodicTable", "Mass"))
        #self.ligClear2.setText(_translate("PeriodicTable", "x"))
        #self.ligClear3.setText(_translate("PeriodicTable", "x"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PeriodicTable = QtWidgets.QWidget()
    ui = Ui_PeriodicTable()
    ui.setupUi(PeriodicTable)
    PeriodicTable.show()
    sys.exit(app.exec_())

